### ISSUE TITLE
add css property "overflow: scroll;" to index.xhtml

### ISSUE THREAD

**Issue by hendrixjoseph** [hendrixjoseph/FamilyTree#31]
Css example:

``` css
div.children {
    width: 150px;
    height: 150px;
    overflow: auto;
} 
```

Needed in children list, source list, extra info list, etc.

See http://www.w3schools.com/cssref/pr_pos_overflow.asp
